import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { DataService } from 'src/app/core/services/data.service';
import { DropsResponse } from 'src/app/core/models/dropsResponse';
import { Banner } from 'src/app/core/models/banner';
import { CollectibleDrop } from 'src/app/core/models/collectibleDrops';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class DraftKingsService extends DataService{

  constructor(http: HttpClient) {
    super(http);
  }

  getDrops(): Observable<DropsResponse> {
    return super._get<DropsResponse>(`marketplaces/v1/drops/`);
  }

  getDropsMockData(): DropsResponse {
    var banner: Banner = {
      url: "https://marketplace.draftkings.com/_assets/banners/images/294d19ba-7404-443f-a77e-ff539f51d4cd.gif",
      destinationUrl: "https://marketplace.draftkings.com/lp/22-augusta-ga-golf-nft-collection",
      openLinkInNewTab: true
    }
    var collectibleDrops: CollectibleDrop[] = [
        {
          "salePrice": 50.00,
          "saleCurrencyCode": "USD",
          "remainingQuantity": 906,
          "primaryPurchaseStatus": "Enabled",
          "dropItemInfoTitle": "Purchase Limit Has Increased!",
          "dropDate": "2022-04-01T20:00:57.0000000+00:00",
          "hasPreferredAccess": false,
          "dropItemDescription": "Individual users can now purchase a maximum of up to 10 editions.",
          "dropItemDescriptionLink": "https://marketplace.draftkings.com/lp/2022-college-hoops-nft-collection",
          "merchandiseType": "Collectible",
          "visibleDate": "2022-03-30T17:00:57.0000000+00:00",
          "collectibleKey": "0a9a17d78bec49c2ad4628eca0570306",
          "name": "Common TourneyToons: Cuttin' Down Nets",
          "description": "The Common TourneyToons: Cuttin' Down Nets collectible is an official DraftKings NFT as a part of the 2022 College Hoops Tournament Collection. This NFT represents one of 2,022 editions. The 2022 College Hoops Collection is the first of many official NFT collections created by DraftKings as part of our new program, the DraftKings Primetime NFT Series. This series will celebrate the biggest moments in sports and will feature NFT drops during primetime events to engage fans like never before. Get rewarded for each collection and experience these major sports moments throughout the year. This collection was created to commemorate the 2022 College Hoops Tournament and will feature several collectible drops throughout the tourney. Gain access to exclusive DK rewards the more you collect, and priority access to a future collection drop in the DraftKings Primetime NFT series for completing the collection. All purchases are subject to DraftKings Terms & Conditions (https://myaccount.draftkings.com/documents/us-mkt-terms-of-use).",
          "partnerName": "DraftKings",
          "totalQuantity": 2022,
          "collectionName": "2022 College Hoops Collection",
          "contractAddress": "0xec5f4ea1f761f507a616e4c6226084ab2f32d218",
          "blockchainName": "Polygon",
          "thumbnailUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/88bdbf63-7390-4545-a3fa-8ac80b0a5d62.png",
          "thumbnailType": "Image",
          "thumbnailMediaType": "image/png",
          "previewUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/b4ef0be7-a344-46d3-9433-fa5cdec2f97a.png",
          "previewType": "Image",
          "previewMediaType": "image/png",
          "assetUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/b6aa153a-b8fa-4022-8f69-a46375a65816.png",
          "assetType": "Image",
          "assetMediaType": "image/png",
          "supplierTermsOfServiceUrl": "https://myaccount.draftkings.com/documents/us-mkt-terms-of-use",
          "royaltyFeeRate": 0.0000,
          "transactionFeeRate": 0.0500,
          "isTransferrable": false
      },
      {
          "salePrice": 40.00,
          "saleCurrencyCode": "USD",
          "remainingQuantity": 502,
          "primaryPurchaseStatus": "Enabled",
          "dropItemInfoTitle": "Purchase Limit Has Increased!",
          "dropDate": "2022-04-06T17:00:34.0000000+00:00",
          "hasPreferredAccess": true,
          "dropItemDescription": "Individual users can now purchase a maximum of up to 10 editions.",
          "dropItemDescriptionLink": "https://marketplace.draftkings.com/lp/22-augusta-ga-golf-nft-collection",
          "preferredAccessStartTime": "2022-04-06T13:00:34.0000000+00:00",
          "preferredAccessEndTime": "2022-04-06T16:30:34.0000000+00:00",
          "merchandiseType": "Collectible",
          "visibleDate": "2022-04-05T22:56:58.0000000+00:00",
          "preferredAccessPrice": 32.00,
          "collectibleKey": "57be55dec1c94b61a0b9273ac95088e6",
          "name": "Common GolfGuys: Perfect Drive",
          "description": "The Common GolfGuys: Perfect Drive collectible is an official DraftKings NFT as a part of the 2022 Augusta, GA Golf Collection. This NFT represents one of 1500 editions. The 2022 Augusta, GA Golf Collection is one of many official NFT collections created by DraftKings as part of our new program, the DraftKings Primetime NFT Series. This series will celebrate the biggest moments in sports and will feature NFT drops during primetime events to engage fans like never before. Get rewarded for each collection and experience these major sports moments throughout the year. This collection was created to commemorate the first major golf tournament of 2022 and will feature several collectible drops. Gain access to exclusive DK rewards the more you collect, and priority access to a future collection drop in the DraftKings Primetime NFT series for completing the collection. All purchases are subject to DraftKings Terms & Conditions (https://myaccount.draftkings.com/documents/us-mkt-terms-of-use).",
          "partnerName": "DraftKings",
          "totalQuantity": 1500,
          "collectionName": "2022 Augusta, GA Golf Collection",
          "contractAddress": "0xec5f4ea1f761f507a616e4c6226084ab2f32d218",
          "blockchainName": "Polygon",
          "thumbnailUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/8f2eda00-ac68-49e0-8651-0e86e4f49ef7.png",
          "thumbnailType": "Image",
          "thumbnailMediaType": "image/png",
          "previewUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/5c2337b0-13f0-4527-b95e-f47b9638704d.png",
          "previewType": "Image",
          "previewMediaType": "image/png",
          "assetUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/a431295e-7b78-4ed4-a840-39ebf8e7482d.png",
          "assetType": "Image",
          "assetMediaType": "image/png",
          "supplierTermsOfServiceUrl": "https://myaccount.draftkings.com/documents/us-mkt-terms-of-use",
          "royaltyFeeRate": 0.0000,
          "transactionFeeRate": 0.0500,
          "isTransferrable": false
      },
      {
          "salePrice": 100.00,
          "saleCurrencyCode": "USD",
          "remainingQuantity": 366,
          "primaryPurchaseStatus": "Enabled",
          "dropItemInfoTitle": "Purchase Limit Has Increased!",
          "dropDate": "2022-04-06T18:00:00.0000000+00:00",
          "hasPreferredAccess": true,
          "dropItemDescription": "Individual users can now purchase a maximum of up to 10 editions.",
          "dropItemDescriptionLink": "https://marketplace.draftkings.com/lp/22-augusta-ga-golf-nft-collection",
          "preferredAccessStartTime": "2022-04-06T13:00:55.0000000+00:00",
          "preferredAccessEndTime": "2022-04-06T17:30:00.0000000+00:00",
          "merchandiseType": "Collectible",
          "visibleDate": "2022-04-05T23:00:08.0000000+00:00",
          "preferredAccessPrice": 80.00,
          "collectibleKey": "da998b9809864b439697bf11edd89532",
          "name": "Rare GolfGuys: Born to Read",
          "description": "The Rare GolfGuys: Born to Read collectible is an official DraftKings NFT as a part of the 2022 Augusta, GA Golf Collection. This NFT represents one of 900 editions. The 2022 Augusta, GA Golf Collection is one of many official NFT collections created by DraftKings as part of our new program, the DraftKings Primetime NFT Series. This series will celebrate the biggest moments in sports and will feature NFT drops during primetime events to engage fans like never before. Get rewarded for each collection and experience these major sports moments throughout the year. This collection was created to commemorate the first major golf tournament of 2022 and will feature several collectible drops. Gain access to exclusive DK rewards the more you collect, and priority access to a future collection drop in the DraftKings Primetime NFT series for completing the collection. All purchases are subject to DraftKings Terms & Conditions (https://myaccount.draftkings.com/documents/us-mkt-terms-of-use).",
          "partnerName": "DraftKings",
          "totalQuantity": 900,
          "collectionName": "2022 Augusta, GA Golf Collection",
          "contractAddress": "0xec5f4ea1f761f507a616e4c6226084ab2f32d218",
          "blockchainName": "Polygon",
          "thumbnailUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/81293e52-7dc2-462b-822a-552be7e4a946.png",
          "thumbnailType": "Image",
          "thumbnailMediaType": "image/png",
          "previewUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/11683bad-b50e-4e94-97b6-c6a7f606ff0c.png",
          "previewType": "Image",
          "previewMediaType": "image/png",
          "assetUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/62d2fd82-e4fb-4f11-beed-af6a910427d3.png",
          "assetType": "Image",
          "assetMediaType": "image/png",
          "supplierTermsOfServiceUrl": "https://myaccount.draftkings.com/documents/us-mkt-terms-of-use",
          "royaltyFeeRate": 0.0000,
          "transactionFeeRate": 0.0500,
          "isTransferrable": false
      },
      {
          "salePrice": 150.00,
          "saleCurrencyCode": "USD",
          "remainingQuantity": 432,
          "primaryPurchaseStatus": "Enabled",
          "dropItemInfoTitle": "Purchase Limit Has Increased!",
          "dropDate": "2022-04-08T17:00:02.0000000+00:00",
          "hasPreferredAccess": true,
          "dropItemDescription": "Individual users can now purchase a maximum of up to 10 editions.",
          "dropItemDescriptionLink": "https://marketplace.draftkings.com/lp/22-augusta-ga-golf-nft-collection",
          "preferredAccessStartTime": "2022-04-08T13:00:00.0000000+00:00",
          "preferredAccessEndTime": "2022-04-08T16:30:00.0000000+00:00",
          "merchandiseType": "Collectible",
          "visibleDate": "2022-04-07T12:59:00.0000000+00:00",
          "preferredAccessPrice": 120.00,
          "collectibleKey": "7fe5350c122e439ba25fb877f5c742b5",
          "name": "Common GolfGuys:  Perfect Drive - Birdie Edition",
          "description": "The Common GolfGuys: Perfect Drive - Birdie Edition collectible is an official DraftKings NFT as a part of the 2022 Augusta, GA Golf Collection. This NFT represents one of 600 editions. The 2022 Augusta, GA Golf Collection is one of many official NFT collections created by DraftKings as part of our new program, the DraftKings Primetime NFT Series. This series will celebrate the biggest moments in sports and will feature NFT drops during primetime events to engage fans like never before. Get rewarded for each collection and experience these major sports moments throughout the year. This collection was created to commemorate the first major golf tournament of 2022 and will feature several collectible drops. Gain access to exclusive DK rewards the more you collect, and priority access to a future collection drop in the DraftKings Primetime NFT series for completing the collection. All purchases are subject to DraftKings Terms & Conditions (https://myaccount.draftkings.com/documents/us-mkt-terms-of-use).",
          "partnerName": "DraftKings",
          "totalQuantity": 600,
          "collectionName": "2022 Augusta, GA Golf Collection",
          "contractAddress": "0xec5f4ea1f761f507a616e4c6226084ab2f32d218",
          "blockchainName": "Polygon",
          "thumbnailUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/8b532008-4f4c-42cd-a6f9-ca141f78c976.png",
          "thumbnailType": "Image",
          "thumbnailMediaType": "image/png",
          "previewUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/453bbd36-c7d8-4c24-a7cd-296dd9b9eebd.png",
          "previewType": "Image",
          "previewMediaType": "image/png",
          "assetUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/7b731514-65c3-440a-8bdc-53b2334f48b9.png",
          "assetType": "Image",
          "assetMediaType": "image/png",
          "supplierTermsOfServiceUrl": "https://myaccount.draftkings.com/documents/us-mkt-terms-of-use",
          "royaltyFeeRate": 0.0000,
          "transactionFeeRate": 0.0500,
          "isTransferrable": false
      },
      {
          "salePrice": 300.00,
          "saleCurrencyCode": "USD",
          "remainingQuantity": 216,
          "primaryPurchaseStatus": "Enabled",
          "dropItemInfoTitle": "Purchase Limit Has Increased!",
          "dropDate": "2022-04-08T18:00:00.0000000+00:00",
          "hasPreferredAccess": true,
          "dropItemDescription": "Individual users can now purchase a maximum of up to 10 editions.",
          "dropItemDescriptionLink": "https://marketplace.draftkings.com/lp/22-augusta-ga-golf-nft-collection",
          "preferredAccessStartTime": "2022-04-08T13:00:00.0000000+00:00",
          "preferredAccessEndTime": "2022-04-08T17:30:00.0000000+00:00",
          "merchandiseType": "Collectible",
          "visibleDate": "2022-04-07T12:59:00.0000000+00:00",
          "preferredAccessPrice": 240.00,
          "collectibleKey": "ab248da3dae74ff785d8d6d60afeb922",
          "name": "Rare GolfGuys: Born to Read - Eagle Edition",
          "description": "The Rare GolfGuys: Born to Read - Eagle Edition collectible is an official DraftKings NFT as a part of the 2022 Augusta, GA Golf Collection. This NFT represents one of 360 editions. The 2022 Augusta, GA Golf Collection is one of many official NFT collections created by DraftKings as part of our new program, the DraftKings Primetime NFT Series. This series will celebrate the biggest moments in sports and will feature NFT drops during primetime events to engage fans like never before. Get rewarded for each collection and experience these major sports moments throughout the year. This collection was created to commemorate the first major golf tournament of 2022 and will feature several collectible drops throughout the tourney. Gain access to exclusive DK rewards the more you collect, and priority access to a future collection drop in the DraftKings Primetime NFT series for completing the collection. All purchases are subject to DraftKings Terms & Conditions (https://myaccount.draftkings.com/documents/us-mkt-terms-of-use).",
          "partnerName": "DraftKings",
          "totalQuantity": 360,
          "collectionName": "2022 Augusta, GA Golf Collection",
          "contractAddress": "0xec5f4ea1f761f507a616e4c6226084ab2f32d218",
          "blockchainName": "Polygon",
          "thumbnailUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/a8cbf2e6-4d39-4779-b68c-eada430de532.png",
          "thumbnailType": "Image",
          "thumbnailMediaType": "image/png",
          "previewUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/08d0fc96-a5b8-4102-a987-8283c3eed6c7.png",
          "previewType": "Image",
          "previewMediaType": "image/png",
          "assetUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/74e3a4d6-1a8b-45e2-90b2-ae82a4204305.png",
          "assetType": "Image",
          "assetMediaType": "image/png",
          "supplierTermsOfServiceUrl": "https://myaccount.draftkings.com/documents/us-mkt-terms-of-use",
          "royaltyFeeRate": 0.0000,
          "transactionFeeRate": 0.0500,
          "isTransferrable": false
      },
      {
          "salePrice": 900.00,
          "saleCurrencyCode": "USD",
          "remainingQuantity": 0,
          "primaryPurchaseStatus": "Enabled",
          "dropDate": "2022-04-08T19:00:00.0000000+00:00",
          "hasPreferredAccess": true,
          "dropItemDescriptionLink": "https://marketplace.draftkings.com/lp/22-augusta-ga-golf-nft-collection",
          "preferredAccessStartTime": "2022-04-08T13:00:00.0000000+00:00",
          "preferredAccessEndTime": "2022-04-08T18:30:00.0000000+00:00",
          "merchandiseType": "Collectible",
          "visibleDate": "2022-04-07T12:59:00.0000000+00:00",
          "preferredAccessPrice": 720.00,
          "collectibleKey": "2bedda659f234d3d8ba270b06cca1764",
          "name": "Elite GolfGuys: A Winning Tradition - Albatross Edition",
          "description": "The Elite GolfGuys: A Winning Tradition - Albatross Edition collectible is an official DraftKings NFT as a part of the 2022 Augusta, GA Golf Collection. This NFT represents one of 72 editions. The 2022 Augusta, GA Golf Collection is one of many official NFT collections created by DraftKings as part of our new program, the DraftKings Primetime NFT Series. This series will celebrate the biggest moments in sports and will feature NFT drops during primetime events to engage fans like never before. Get rewarded for each collection and experience these major sports moments throughout the year. This collection was created to commemorate the first major golf tournament of 2022 and will feature several collectible drops. Gain access to exclusive DK rewards the more you collect, and priority access to a future collection drop in the DraftKings Primetime NFT series for completing the collection. All purchases are subject to DraftKings Terms & Conditions (https://myaccount.draftkings.com/documents/us-mkt-terms-of-use).",
          "partnerName": "DraftKings",
          "totalQuantity": 72,
          "collectionName": "2022 Augusta, GA Golf Collection",
          "contractAddress": "0xec5f4ea1f761f507a616e4c6226084ab2f32d218",
          "blockchainName": "Polygon",
          "thumbnailUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/83b6136a-eee6-43f1-8426-3068df275efb.png",
          "thumbnailType": "Image",
          "thumbnailMediaType": "image/png",
          "previewUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/41b301cc-d52d-4d0f-b08e-29d162d08cdf.png",
          "previewType": "Image",
          "previewMediaType": "image/png",
          "assetUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/fd324272-7ca4-4682-9aaa-3be5d3321906.png",
          "assetType": "Image",
          "assetMediaType": "image/png",
          "supplierTermsOfServiceUrl": "https://myaccount.draftkings.com/documents/us-mkt-terms-of-use",
          "royaltyFeeRate": 0.0000,
          "transactionFeeRate": 0.0500,
          "isTransferrable": false
      },
      {
          "salePrice": 500.00,
          "saleCurrencyCode": "USD",
          "remainingQuantity": 0,
          "primaryPurchaseStatus": "Enabled",
          "waitingRoomKey": "f6256fdc9fb5424aa3c2",
          "dropDate": "2022-04-06T21:00:48.0000000+00:00",
          "hasPreferredAccess": false,
          "dropItemDescriptionLink": "https://blog.autograph.io/details/624ba853ecebf7001439da3e/post",
          "merchandiseType": "Collectible",
          "visibleDate": "2022-04-06T13:30:48.0000000+00:00",
          "collectibleKey": "f6256fdc9fb5424aa3c2c27938293432",
          "name": "Tom Brady: Man in the Arena",
          "description": "\"The Tom Brady: Man in the Arena is an official Autograph NFT offered as part of The Man in the Arena Collection. By purchasing, you agree to the Terms and Conditions (https://terms.autograph.io/mita1.pdf) and Autograph's Terms Of Service (https://go.autograph.io/tos). \nESPN and all related content and elements are trademarks of and © ESPN.\"",
          "partnerName": "Autograph",
          "totalQuantity": 50,
          "collectionName": "Man in the Arena: Tom Brady Collection",
          "contractAddress": "0x57e4Bd0Fe8C47a0d1b78dE67039e6727Af6857C2",
          "blockchainName": "Polygon",
          "thumbnailUrl": "https://media.autograph.io/image/00cc7500-bc7f-421e-802f-c9113e147f89_original_.png",
          "thumbnailType": "Image",
          "thumbnailMediaType": "image/png",
          "previewUrl": "https://media.autograph.io/18d399f7-22a3-46fa-814f-8f84c25e2c34_original_.mp4",
          "previewType": "Video",
          "previewMediaType": "video/mp4",
          "assetUrl": "https://media.autograph.io/e566467e-f994-4f3f-8a5d-dbd2ca13b04a_original_.mp4",
          "assetType": "Video",
          "assetMediaType": "video/mp4",
          "partnerAssetUrl": "https://autograph.io/details/624a113cbd88be0013f2b6f9/nft",
          "supplierTermsOfServiceUrl": "https://go.autograph.io/tos",
          "rarityCallout": "Individually signed editions",
          "royaltyFeeRate": 0.1000,
          "transactionFeeRate": 0.0500,
          "isTransferrable": false
      },
      {
          "salePrice": 250.00,
          "saleCurrencyCode": "USD",
          "remainingQuantity": 0,
          "primaryPurchaseStatus": "Enabled",
          "waitingRoomKey": "b417ecc607044b5ab6dc",
          "dropDate": "2022-04-06T20:00:00.0000000+00:00",
          "hasPreferredAccess": false,
          "dropItemDescriptionLink": "https://blog.autograph.io/details/624ba853ecebf7001439da3e/post",
          "merchandiseType": "Collectible",
          "visibleDate": "2022-04-06T13:30:00.0000000+00:00",
          "collectibleKey": "b417ecc607044b5ab6dc97bd1816c19d",
          "name": "Tom Brady: Legacy",
          "description": "\"The Tom Brady: Legacy is an official Autograph NFT offered as part of The Man in the Arena Collection. By purchasing, you agree to the Terms and Conditions (https://terms.autograph.io/mita1.pdf) and Autograph's Terms Of Service (https://go.autograph.io/tos). \nESPN and all related content and elements are trademarks of and © ESPN.\"",
          "partnerName": "Autograph",
          "totalQuantity": 100,
          "collectionName": "Man in the Arena: Tom Brady Collection",
          "contractAddress": "0x57e4Bd0Fe8C47a0d1b78dE67039e6727Af6857C2",
          "blockchainName": "Polygon",
          "thumbnailUrl": "https://media.autograph.io/MITA_Legacy_StillZ93FgAZ8t5fba1dWrMunwG5q.png",
          "thumbnailType": "Image",
          "thumbnailMediaType": "image/png",
          "previewUrl": "https://media.autograph.io/MITA_Legacy_PreviewoXxkfz5cRLibOJfmSOxuFECO.mp4",
          "previewType": "Video",
          "previewMediaType": "video/mp4",
          "assetUrl": "https://media.autograph.io/MITA_Legacy_Hi_ResHjvw33vuj6EBMzl1KPVfkvFO.mp4",
          "assetType": "Video",
          "assetMediaType": "video/mp4",
          "partnerAssetUrl": "https://autograph.io/details/624c70448d543600158055fa/nft",
          "supplierTermsOfServiceUrl": "https://go.autograph.io/tos",
          "royaltyFeeRate": 0.1000,
          "transactionFeeRate": 0.0500,
          "isTransferrable": false
      },
      {
          "salePrice": 100.00,
          "saleCurrencyCode": "USD",
          "remainingQuantity": 0,
          "primaryPurchaseStatus": "Enabled",
          "waitingRoomKey": "ec1f1ba899b1410d9691",
          "dropDate": "2022-04-06T19:00:58.0000000+00:00",
          "hasPreferredAccess": false,
          "dropItemDescriptionLink": "https://blog.autograph.io/details/624ba853ecebf7001439da3e/post",
          "merchandiseType": "Collectible",
          "visibleDate": "2022-04-06T13:30:58.0000000+00:00",
          "collectibleKey": "ec1f1ba899b1410d9691d172fa680ced",
          "name": "Tom Brady: Greatest of All Time",
          "description": "\"The Tom Brady: Greatest of All Time is an official Autograph NFT offered as part of The Man in the Arena Collection. By purchasing, you agree to the Terms and Conditions (https://terms.autograph.io/mita1.pdf) and Autograph's Terms Of Service (https://go.autograph.io/tos). \nESPN and all related content and elements are trademarks of and © ESPN.\"",
          "partnerName": "Autograph",
          "totalQuantity": 250,
          "collectionName": "Man in the Arena: Tom Brady Collection",
          "contractAddress": "0x57e4Bd0Fe8C47a0d1b78dE67039e6727Af6857C2",
          "blockchainName": "Polygon",
          "thumbnailUrl": "https://media.autograph.io/MITA_Greatest_of_all_Time_Stillp5RnHFaMTkXcMMhhxEM4VBSR.png",
          "thumbnailType": "Image",
          "thumbnailMediaType": "image/png",
          "previewUrl": "https://media.autograph.io/MITA_Greatest_of_all_Time_Previewbpp4Y9IUXvduPiBjdIJSlV5v.mp4",
          "previewType": "Video",
          "previewMediaType": "video/mp4",
          "assetUrl": "https://media.autograph.io/MITA_Greatest_of_all_Time_HiResxXoc0i1Lc1O2tKjhCQwqzwsb.mp4",
          "assetType": "Video",
          "assetMediaType": "video/mp4",
          "partnerAssetUrl": "https://autograph.io/details/624c6f4f8d543600158054da/nft",
          "supplierTermsOfServiceUrl": "https://go.autograph.io/tos",
          "royaltyFeeRate": 0.1000,
          "transactionFeeRate": 0.0500,
          "isTransferrable": false
      },
      {
          "salePrice": 400.00,
          "saleCurrencyCode": "USD",
          "remainingQuantity": 0,
          "primaryPurchaseStatus": "Enabled",
          "waitingRoomKey": "86d602be592c48b78569",
          "dropDate": "2022-04-06T19:00:06.0000000+00:00",
          "hasPreferredAccess": true,
          "dropItemDescriptionLink": "https://marketplace.draftkings.com/lp/22-augusta-ga-golf-nft-collection",
          "preferredAccessStartTime": "2022-04-06T13:00:06.0000000+00:00",
          "preferredAccessEndTime": "2022-04-06T18:30:00.0000000+00:00",
          "merchandiseType": "Collectible",
          "visibleDate": "2022-04-05T23:01:05.0000000+00:00",
          "preferredAccessPrice": 320.00,
          "collectibleKey": "86d602be592c48b785693c17c884eeac",
          "name": "Elite GolfGuys: A Winning Tradition",
          "description": "The Elite GolfGuys: A Winning Tradition collectible is an official DraftKings NFT as a part of the 2022 Augusta, GA Golf Collection. This NFT represents one of 180 editions. The 2022 Augusta, GA Golf Collection is one of many official NFT collections created by DraftKings as part of our new program, the DraftKings Primetime NFT Series. This series will celebrate the biggest moments in sports and will feature NFT drops during primetime events to engage fans like never before. Get rewarded for each collection and experience these major sports moments throughout the year. This collection was created to commemorate the first major golf tournament of 2022 and will feature several collectible drops. Gain access to exclusive DK rewards the more you collect, and priority access to a future collection drop in the DraftKings Primetime NFT series for completing the collection. All purchases are subject to DraftKings Terms & Conditions (https://myaccount.draftkings.com/documents/us-mkt-terms-of-use).",
          "partnerName": "DraftKings",
          "totalQuantity": 180,
          "collectionName": "2022 Augusta, GA Golf Collection",
          "contractAddress": "0xec5f4ea1f761f507a616e4c6226084ab2f32d218",
          "blockchainName": "Polygon",
          "thumbnailUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/7105f6a2-842c-4e07-9f32-2f38677715d7.png",
          "thumbnailType": "Image",
          "thumbnailMediaType": "image/png",
          "previewUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/7037c633-e482-4a34-906d-486e3fa56a97.png",
          "previewType": "Image",
          "previewMediaType": "image/png",
          "assetUrl": "https://marketplace.draftkings.com/_assets/collectibles/assets/54b252b1-69af-4364-a97e-51fcd95a8b5b.png",
          "assetType": "Image",
          "assetMediaType": "image/png",
          "supplierTermsOfServiceUrl": "https://myaccount.draftkings.com/documents/us-mkt-terms-of-use",
          "royaltyFeeRate": 0.0000,
          "transactionFeeRate": 0.0500,
          "isTransferrable": false
      }
    ];
    var response: DropsResponse = {
      banner: banner,
      collectibleDrops: collectibleDrops
    };
    return response;
  }
}
